version: '3.4'

services:
  database:
    container_name: database
    restart: always
    image: postgres:latest
    env_file:
      - dev_env
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init_dev.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    restart: always
    ports:
      - "5432:5432"
    depends_on:
      - database
    env_file:
      - dev_env
    links:
        - database:database

  nginx:
    image: "nginx:1.13.5"
    ports:
      - "85:85"
    volumes:
      - ./nginx_conf_dev:/etc/nginx/conf.d
    depends_on: 
      - app

volumes:
  db:
    driver: local

