version: '3.4'

services:
  database:
    container_name: database-prod
    restart: always
    image: bitnami/postgresql:11.15.0
    env_file:
      - .env
#    ports:
#      - "5432:5432"
    volumes:
      - db:/bitnami/postgresql
      - ./init_prod.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    env_file:
      - .env
#    command: python run.py
    command: gunicorn -w 4 --threads 4 --bind :4999 run:app

  nginx:
    image: "nginx:1.13.5"
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  db: