version: '3.4'

services:
  database:
    container_name: database
    restart: always
    image: bitnami/postgresql:11.15.0
    env_file:
      - dev_env
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./init_dev.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    restart: always
    depends_on:
      - database
    links:
      - database:database
    env_file:
      - dev_env
    command: gunicorn -w 4 --threads 4 --bind :4998 run:app

  nginx:
    image: "nginx:1.13.5"
    ports:
      - "85:85"
    volumes:
      - ./nginx_conf_dev:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  db:
